In [1]:
import pandas as pd

In [3]:
df=pd.read_excel("BackOrder Oct-Dic 2024.xlsx")
df.head()

,ID Usuario,SAC_Nombre,ID Cliente,Cliente,Credito Lib,F.Captura,F. Necesidad,F. Embarque,OC Cliente,O.V.,...,Antiguedad,Enviado a Greycon (SAC),Procesado en Greycon,Ordenes Cerradas Procesadas,OV Cancelada,OV Abierta,OV-Lin Abierta,OV-Lin Cancelada,OV-Lin-Lib Abierta,OV-Lin-Lib Cancelada
0,ktellez,SAC-04 K. TELLEZ,33029,"EL PASO PAPER BOX, INC",True,2024-11-12,2024-11-15,2024-11-15,8375,139115,...,31-60 dias,True,True,1,False,False,False,False,False,False
1,ktellez,SAC-04 K. TELLEZ,33029,"EL PASO PAPER BOX, INC",True,2024-11-12,2024-12-25,2024-12-25,8375,139115,...,31-60 dias,False,False,0,False,False,False,True,False,True
2,ktellez,Ventas de la Casa,33990,STOCK EL PASO PAPER BOX,True,2024-11-12,2024-11-15,2024-11-15,cabo14,139116,...,31-60 dias,True,True,1,True,False,False,True,False,True
3,ktellez,Ventas de la Casa,33990,STOCK EL PASO PAPER BOX,True,2024-11-20,2024-11-21,2024-11-21,TRIM WWF,139240,...,31-60 dias,True,True,1,True,False,False,True,False,True
4,ktellez,SAC-04 K. TELLEZ,33029,"EL PASO PAPER BOX, INC",True,2024-12-19,2024-12-21,2024-12-21,8498,139842,...,0-30 dias,True,True,1,False,False,False,False,False,False

In [4]:
df.describe()

,ID Cliente,O.V.,Linea,Lib,Ancho,Largo,Hojeo Solicitado,Hojeo Embarcadas,Hojeo Pendientes,Hojeo Inv Asignadas,...,Diam_Interior,gms/m2 (Greycon),P.MSF,Cant_Producida,PO Line,Fecha Referencia,Dias_Diferencia,FOB,Dias_Antiguedad,Ordenes Cerradas Procesadas
count,4812.000000,4812.000000,4812.000000,4812.0,4812.000000,4812.000000,4812.000000,4812.000000,4812.000000,4812.000000,...,186.000000,4812.000000,4812.0,0.0,0.0,0.0,2644.000000,0.0,4812.000000,4812.000000
mean,19055.323774,139164.725894,9.634871,1.0,158.060304,9.108218,2066.520037,1773.935562,292.584475,0.020818,...,6.795699,271.634456,0.0,NaN,NaN,NaN,-3.283661,NaN,46.316916,0.597880
std,6983.299411,496.513015,23.549492,0.0,3582.886791,25.975175,13218.532625,11876.760564,5867.450311,1.441577,...,3.824697,121.599222,0.0,NaN,NaN,NaN,14.058190,NaN,25.840081,0.490377
min,8005.000000,137527.000000,1.000000,1.0,5.000000,0.000000,0.000000,0.000000,-570.000299,0.000000,...,4.000000,0.000000,0.0,NaN,NaN,NaN,-149.000000,NaN,0.000000,0.000000
25%,15113.500000,138731.000000,1.000000,1.0,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,160.000000,0.0,NaN,NaN,NaN,-7.000000,NaN,25.000000,0.000000
50%,19249.000000,139194.000000,3.000000,1.0,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,251.000000,0.0,NaN,NaN,NaN,-1.000000,NaN,46.000000,1.000000
75%,19492.000000,139619.000000,8.000000,1.0,126.800000,0.000000,0.000000,0.000000,0.000000,0.000000,...,12.000000,362.000000,0.0,NaN,NaN,NaN,2.000000,NaN,68.000000,1.000000
max,37000.000000,139996.000000,204.000000,1.0,248609.000000,150.500000,300000.000000,300000.000000,231801.000028,100.000000,...,12.000000,535.000000,0.0,NaN,NaN,NaN,98.000000,NaN,90.000000,1.000000

In [5]:
df.shape

(4812, 81)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Data columns (total 81 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ID Usuario                      4812 non-null   object
 1   SAC_Nombre                      4812 non-null   object
 2   ID Cliente                      4812 non-null   int64
 3   Cliente                         4812 non-null   object
 4   Credito Lib                     4812 non-null   bool
 5   F.Captura                       4812 non-null   datetime64[ns]
 6   F. Necesidad                    4776 non-null   datetime64[ns]
 7   F. Embarque                     4776 non-null   datetime64[ns]
 8   OC Cliente                      4809 non-null   object
 9   O.V.                            4812 non-null   int64
 10  Linea                           4812 non-null   int64
 11  Lib                             4812 non-null   int64
 12  Producto                        4812 non-null   object
 13  Maquina                         4812 non-null   object
 14  Exp                             4812 non-null   object
 15  Parte                           4812 non-null   object
 16  UOMVenta                        4812 non-null   object
 17  Calidad                         4812 non-null   object
 18  Ancho                           4812 non-null   float64
 19  Largo                           4812 non-null   float64
 20  UD_Ancho                        4812 non-null   object
 21  UM_Hojeo                        612 non-null    object
 22  Hojeo Solicitado                4812 non-null   float64
 23  Hojeo Embarcadas                4812 non-null   float64
 24  Hojeo Pendientes                4812 non-null   float64
 25  Hojeo Inv Asignadas             4812 non-null   float64
 26  Hojeo Pendiente Fabricar        4812 non-null   float64
 27  OT_Hojeo                        4812 non-null   int64
 28  Rev_Hojeo                       0 non-null      float64
 29  Hojas Inv No Asignado           4812 non-null   int64
 30  UdeM                            4812 non-null   object
 31  TON Solicitadas                 4812 non-null   float64
 32  TON Embarcadas                  4812 non-null   float64
 33  TON Pendientes                  4812 non-null   float64
 34  TON Inv_Asignado                4812 non-null   float64
 35  Ton Inv Asignado 8888 p/Hojear  4812 non-null   float64
 36  TON Pendiente Fabricar          4812 non-null   float64
 37  OT_Molino                       4812 non-null   int64
 38  Ton Inv_NOAsignado              4812 non-null   float64
 39  PU                              4812 non-null   float64
 40  Calle                           4375 non-null   object
 41  City                            4373 non-null   object
 42  Agente_Creditos                 4383 non-null   object
 43  Especificacion                  0 non-null      float64
 44  Via_Embarque                    2427 non-null   object
 45  Diam_Exterior                   186 non-null    float64
 46  Diam_Interior                   186 non-null    float64
 47  Cara                            186 non-null    object
 48  Centro                          417 non-null    object
 49  Confirmado                      4812 non-null   bool
 50  Mail                            4812 non-null   bool
 51  Correos                         2901 non-null   object
 52  Venta_Inventario                4812 non-null   bool
 53  Hojear_enPromasa                4812 non-null   bool
 54  gms/m2 (Greycon)                4812 non-null   int64
 55  Lista Pr                        4292 non-null   object
 56  P.MSF                           4812 non-null   int64
 57  SAC_Rep                         4812 non-null   object
 58  Comentario_OV                   301 non-null    object
 59  Cant_Producida                  0 non-null      float64
 60  Estado a Embarcar               4373 non-null   object
 61  PaÃ­s a Embarcar                 4812 non-null   object
 62  PO Line                         0 non-null      float64
 63  Fecha Referencia                0 non-null      float64
 64  Fecha_Inicial_Curva             2644 non-null   datetime64[ns]
 65  Fecha_Final_Curva               2644 non-null   datetime64[ns]
 66  Dias_Diferencia                 2644 non-null   float64
 67  FOB                             0 non-null      float64
 68  Requiere_Cita                   3825 non-null   object
 69  Enviar_a_ALFA                   4812 non-null   bool
 70  Dias_Antiguedad                 4812 non-null   int64
 71  Antiguedad                      4812 non-null   object
 72  Enviado a Greycon (SAC)         4812 non-null   bool
 73  Procesado en Greycon            4812 non-null   bool
 74  Ordenes Cerradas Procesadas     4812 non-null   int64
 75  OV Cancelada                    4812 non-null   bool
 76  OV Abierta                      4812 non-null   bool
 77  OV-Lin Abierta                  4812 non-null   bool
 78  OV-Lin Cancelada                4812 non-null   bool
 79  OV-Lin-Lib Abierta              4812 non-null   bool
 80  OV-Lin-Lib Cancelada            4812 non-null   bool
dtypes: bool(14), datetime64[ns](5), float64(24), int64(11), object(27)
memory usage: 2.5+ MB

In [9]:
df.dtypes

ID Usuario              object
SAC_Nombre              object
ID Cliente               int64
Cliente                 object
Credito Lib               bool
                         ...
OV Abierta                bool
OV-Lin Abierta            bool
OV-Lin Cancelada          bool
OV-Lin-Lib Abierta        bool
OV-Lin-Lib Cancelada      bool
Length: 81, dtype: object

In [10]:
df.columns

Index(['ID Usuario', 'SAC_Nombre', 'ID Cliente', 'Cliente', 'Credito Lib',
       'F.Captura', 'F. Necesidad', 'F. Embarque', 'OC Cliente', 'O.V.',
       'Linea', 'Lib', 'Producto', 'Maquina', 'Exp', 'Parte', 'UOMVenta',
       'Calidad', 'Ancho', 'Largo', 'UD_Ancho', 'UM_Hojeo', 'Hojeo Solicitado',
       'Hojeo Embarcadas', 'Hojeo Pendientes', 'Hojeo Inv Asignadas',
       'Hojeo Pendiente Fabricar', 'OT_Hojeo', 'Rev_Hojeo',
       'Hojas Inv No Asignado', 'UdeM', 'TON Solicitadas', 'TON Embarcadas',
       'TON Pendientes', 'TON Inv_Asignado', 'Ton Inv Asignado 8888 p/Hojear',
       'TON Pendiente Fabricar', 'OT_Molino', 'Ton Inv_NOAsignado', 'PU',
       'Calle', 'City', 'Agente_Creditos', 'Especificacion', 'Via_Embarque',
       'Diam_Exterior', 'Diam_Interior', 'Cara', 'Centro', 'Confirmado',
       'Mail', 'Correos', 'Venta_Inventario', 'Hojear_enPromasa',
       'gms/m2 (Greycon)', 'Lista Pr', 'P.MSF', 'SAC_Rep', 'Comentario_OV',
       'Cant_Producida', 'Estado a Embarcar', 'PaÃ­s a Embarcar', 'PO Line',
       'Fecha Referencia', 'Fecha_Inicial_Curva', 'Fecha_Final_Curva',
       'Dias_Diferencia', 'FOB', 'Requiere_Cita', 'Enviar_a_ALFA',
       'Dias_Antiguedad', 'Antiguedad', 'Enviado a Greycon (SAC)',
       'Procesado en Greycon', 'Ordenes Cerradas Procesadas', 'OV Cancelada',
       'OV Abierta', 'OV-Lin Abierta', 'OV-Lin Cancelada',
       'OV-Lin-Lib Abierta', 'OV-Lin-Lib Cancelada'],
      dtype='object')

In [12]:
df['Ancho'].describe()

count      4812.000000
mean        158.060304
std        3582.886791
min           5.000000
25%          65.000000
50%          90.000000
75%         126.800000
max      248609.000000
Name: Ancho, dtype: float64

In [13]:
df=df[df['Ancho']<334] #El ancho maximo de deberia de ser 334

In [15]:
df['Ancho'].describe()

count    4810.000000
mean      106.195880
std        60.046023
min         5.000000
25%        65.000000
50%        90.000000
75%       126.800000
max       250.000000
Name: Ancho, dtype: float64